add_newline = false

[character]      # The name of the module we are configuring is "character"
symbol = "â†’"     # The "symbol" segment is being set to "âœ"
style = "dimmed"

prompt_order=["line_break","package","line_break","character"]

[battery]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

# [directory]
# style = "fg:fg"

[git_branch]
symbol = ""
style = "purple"
truncation_length = 32
truncation_symbol = "â€¦"

[git_commit]
commit_hash_length = 4

[git_status]
style = "purple"
# conflicted = "ğŸ³"
ahead = "â†‘"
behind = "â†“"
# diverged = "ğŸ˜µ"
untracked = "?"
# stashed = "ğŸ“¦"
modified = "M"
# staged.value = "++"
# staged.style = "green"
# staged_count.enabled = true
# staged_count.style = "green"
renamed = "R"
deleted = "D"
