add_newline = false

[character]      # The name of the module we are configuring is "character"
symbol = "❯"     # The "symbol" segment is being set to "➜"
vicmd_symbol = "❮"
error_symbol = "x"
use_symbol_for_status = false
# style_success = ""

prompt_order=["line_break","package","line_break","character"]

[battery]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[directory]
style = ""
fish_style_pwd_dir_length = 1

[git_branch]
style = ""
symbol = ""
truncation_length = 32
truncation_symbol = "…"

[git_commit]
commit_hash_length = 4

[git_status]
# style = ""
# conflicted = ""
ahead = "↑"
behind = "↓"
# diverged = ""
untracked = "?"
# stashed = ""
modified = "M"
# staged.value = "++"
# staged.style = "green"
# staged_count.enabled = true
# staged_count.style = "green"
renamed = "R"
deleted = "D"

[cmd_duration]
min_time = 500
prefix = ""
